### ISSUE TITLE
import module failed

### ISSUE THREAD

**Issue by joukio** [jamesremuscat/avx#80]
hi,

I have tried it on the latest ubuntu and the latest fedora release, but when I install avx as the readme suggests I always get importerrors.

Way to reproduce:
- install fedora/ubuntu
- install all requirements as said on the wiki
- create test config with content from the wiki
- run avx-controller -c $test_config_file

Output is always something like:
root@localhost /]# avx-controller -c /root/test.conf  -d
2018-12-25 00:53:33,278 INFO: Starting sequencer loop
2018-12-25 00:53:33,283 INFO: Starting avx controller v1.3.1
2018-12-25 00:53:33,284 INFO: Creating device Main
Traceback (most recent call last):
  File "/usr/bin/avx-controller", line 11, in <module>
    load_entry_point('avx==1.3.1.dev0', 'console_scripts', 'avx-controller')()
  File "build/bdist.linux-x86_64/egg/avx/controller/Controller.py", line 294, in main
  File "build/bdist.linux-x86_64/egg/avx/controller/Controller.py", line 70, in loadConfig
  File "build/bdist.linux-x86_64/egg/avx/devices/Device.py", line 37, in create
  File "build/bdist.linux-x86_64/egg/avx/devices/Device.py", line 45, in get_class
ImportError: No module named KramerVP88

When I manually try to import the KramerVP88 module it also fails, unless I am in the directory where it is located.

**Comment by jamesremuscat** [comment]
Oops, the example config in the README is out of date. It uses the device class `avx.devices.KramerVP88.KramerVP88`, but in fact that should be `avx.devices.serial.KramerVP88.KramerVP88`.
